### PR TITLE
Deploy pages

### PR DESCRIPTION
**Pull request by mahmud1**
- [x] Update [ci.yml](https://github.com/luhipi/sarvey/blob/ci-docs/.github/workflows/ci.yml).
- [x] Update [README.rst](https://github.com/luhipi/sarvey/blob/ci-docs/README.rst).
- [x] Configure GitHub Pages.

### CODE REVIEW

**Comment by Andreas-Piter** [comment]
🎉 Docs are available! 🎉

**Comment by mahmud1** [comment]
- [ ] Update [ci.yml](https://github.com/luhipi/sarvey/blob/ci-docs/.github/workflows/ci.yml).
- [ ] Update [README.rst](https://github.com/luhipi/sarvey/blob/ci-docs/README.rst).
- [ ] Configure GitHub Pages.
- [ ] Add Deployment protection rules for gh-pages.

**Comment by mahmud1** [comment]
Deployment protection rules for gh-pages should be added later.

**Review by Andreas-Piter — APPROVED** [review]
For me it is fine. We need another PR to fix the environment.

**Pull request merged**
