### PR TITLE
Add scientific colormaps 

### PR DESCRIPTION
**Pull request by Andreas-Piter**
sarvey_plot:
- [x] -m
     - [x] map_spatiotemporal_consistency.png and map_coherence.png seem to use the same colormaps, but they run in different directions. This is somewhat counter-intuitive.
     - [x] different default colormaps for velocity and DEM correction. (vanimo)
     - [x] revert colormaps for spatiotemporal consistency
     - [x] remove squared sum of residuals
- [x]  -t
    - [x] different default colormaps for velocity and DEM correction (vanimo)
- [x] -i: change to RomaO
- [x] -p: change to RomaO

sarvey MTI:
- [x] different default colormaps for velocity and DEM correction (vanimo)
- [x] revert colormaps for 
     - [x] temporal autocorrelation
     - [x] RMSE of DEM correction and mean velocity
- [x] create new issue for creating config file with default parameters for plotting

General:
- [x]  Update history
- [ ] Create new tag

### CODE REVIEW

**Comment by Andreas-Piter** [comment]
I did not find a suitable substitute for the cmy colormap from mintpy when displaying interferograms.

grafik
CMY colormap from mintpy.


grafik
bamO colormap from crameri

**Comment by mahmud1** [comment]
The velocity appears good with the new colormap. For the interferogram, I also couldn’t find any suitable colormap in cmcrameri options. I suggest we stick with the current one.

A few suggestions:
• It would be good to have different default colormaps for velocity and DEM correction.
• It would also be useful to allow specifying the colormap as an input argument to sarvey_plot, so if someone prefers something like jet or any other cmcrameri option, they can choose it. I am not sure how complicated this might be for `-t` that has different colormaps.
• map_spatiotemporal_consistency.png and map_coherence.png seem to use the same colormaps, but they run in different directions. This is somewhat counter-intuitive.

**Comment by Andreas-Piter** [comment]
Thanks @mahmud1, for your suggestions. I have updated the ToDo list in the top of this Pull request accordingly.

**Comment by mahmud1** [comment]
> For this example the colormap RomaO seems okay to me: grafik
> 
> What do you think, @mahmud1 ?

The new interfeorgram colormap looks good to me.

**Review by mahmud1 — APPROVED** [review]

**Review by mahmud1 — APPROVED** [review]

**Pull request merged**
